services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: upkeep
      MYSQL_USER: upkeep
      MYSQL_PASSWORD: upkeeppass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"        # Changed port to avoid conflict with local MySQL
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  dbdata:
